backend:
    name: github
    repo: tidaltheory/tidaltheory-www
    branch: trunk
    squash_merges: true

media_library:
    name: uploadcare
    config:
        publicKey: 525235c9c7ef422f4e92
        previewStep: true
        clearable: true

collections:
    - name: work
      label: Work
      folder: work
      create: true
      slug: '{{slug}}'
      fields:
          - { label: Title, name: title, widget: string }
          - { label: Tagline, name: tagline, widget: string }
          - label: Cover image
            name: cover
            widget: image
            allow_multiple: false
          - label: Icon
            name: icon
            widget: image
            allow_multiple: false
          - { label: Publish Date, name: date, widget: date }
          - { label: Intro, name: intro, widget: markdown }
          - { label: Body, name: body, widget: markdown }
          - { label: Category, name: category, widget: list }
          - { label: Tags, name: tags, widget: list }
          - { label: URL, name: url, widget: string }
          - label: Collaborators
            name: collaborators
            widget: markdown

    - name: projects
      label: Projects
      label_singular: Project
      folder: projects
      create: true
      slug: '{{slug}}'
      fields:
          - { label: Title, name: title, widget: string }
          - { label: URL, name: url, widget: string }
          - { label: Description, name: description, widget: markdown }
          - { label: Category, name: category, widget: list }

    - name: galleries
      label: Galleries
      label_singular: Gallery
      folder: photos
      create: true
      slug: '{{slug}}'
      fields:
          - { label: Title, name: title, widget: string }
          - label: Banner
            name: banner
            widget: image
            allow_multiple: false
          - { label: Description, name: description, widget: markdown }
          - label: Images
            name: images
            widget: list
            fields:
                - { name: image, label: Image, widget: image }
                - { name: alt, label: Alt, widget: string, required: false }
                - { name: title, label: Title, widget: string, required: false }
          - { label: Category, name: category, widget: list }
