backend:
  name: github
  repo: tidaltheory/tidaltheory-www
  branch: main
  squash_merges: true

media_folder: static/media
public_folder: /media

collections:
  - name: notes
    label: Notes
    label_singular: Note
    folder: content/notes
    create: true
    format: toml-frontmatter
    identifier_field: date
    slug: '{{date | date('x')}}'
    fields:
      - { label: Date, name: date, widget: datetime }
      - { label: Updated, name: updated, widget: datetime }
      - { label: Content, name: content, widget: markdown }
      - label: Syndication
        name: syndication
        widget: list
        required: false
        fields:
          - { label: URL, name: url, widget: string }
