[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  external_node_modules = ["mdsvex"]

[[headers]]
  ## https://answers.netlify.com/t/content-type-header-not-working-in-netlify-toml/7718
  for = "/*"
[headers.values]
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  X-Clacks-Overhead = "GNU Terry Pratchett"
  X-Content-Type-Options = "nosniff"
  # cache just over 1 hour for webpagetest to be happy
  Cache-Control = "public, max-age=4000"
