[[updates]]
  _type = 'gallery-update'
  date = 2023-01-14
  gallery = '/screen-shots/a-plague-tale-innocence'
  image-count = 4

[[updates]]
  _type = 'post-add'
  date = 2022-12-17
  slug = 'difference-single-key-light-can-make'
  title = 'The difference a single key light can make'
  excerpt = 'Being able to add even just a single extra light to a scene allows for many more options in composing a shot.'

[[updates]]
  _type = 'gallery-add'
  date = 2022-11-29T06:40:36.000Z
  gallery = '/screen-shots/a-plague-tale-innocence'
  title = 'A Plague Tale: Innocence'
  cover = 'apt-innocence_20221128214433'

[[updates]]
  _type = 'gallery-add'
  date = 2022-10-09T04:58:08.000Z
  gallery = '/screen-shots/the-last-of-us-part-i'
  title = 'The Last of Us Part I'
  cover = 'tlou1_20221008221710'
