title = 'You can never look at the same photograph twice'
excerpt = 'Social media feeds are a stream you can step into again and again, but you aren’t always the same person each time.'
posted = 2023-05-07T21:31:45.805Z

[[blocks]]
  type = 'markdown'
  markdown = '''
In a [recent episode of Photomode Unplugged](https://youtu.be/p1WToiw4mV4?t=726), hosts Mik and Rúben were discussing the merits of posting “old” content. I tend to agree with them in that I’m resistant to the idea that art — virtual photography specifically — is or should be&nbsp;disposable.

Most of the discussion was around the trend in social media to post only the latest games or your most recent shots and never think about them after the 24 minutes the average post lives for. One interesting point was about not worrying too much about whether your followers might have already seen an image you’ve posted before, and that this might actually be a good&nbsp;thing!

The idea that an image might hit differently depending on when it’s viewed really resonated with me. It reminded me of this quote from renowned landscape photographer, Ansel&nbsp;Adams:
'''

[[blocks]]
  type = 'blockquote'
  quote = '…there are always two people in every picture: the photographer and the viewer.'
  source = 'Ansel Adams, from <a href="https://www.davidsheff.com/ansel-adams">an interview</a> in <cite>Playboy</cite>, March&nbsp;1983'

[[blocks]]
  type = 'markdown'
  markdown = '''
I’ve always considered this from the perspective of the photographer, putting some of yourself into every picture you make. But each viewer brings their own perspective and circumstances to the picture they’re observing, circumstances that are different each time and can affect the perception of that picture. Although we can do things to give our work the best presentation we can —  reposting to platforms with better image quality, curating images into small sets, etc. — there’s only so much we can do to affect the viewing experience of someone&nbsp;else.

In the age of social media, it’s helpful to remember this when a post isn’t getting the reaction you hoped for, and consider giving some of your older work a second chance&nbsp;too.
'''
