title = 'The difference a single key light can make'
excerpt = 'Being able to add even just a single extra light to a scene allows for a lot more options in composing a shot.'
posted = 2022-12-17
updated = 2022-12-17

[[blocks]]
  type = 'markdown'
  markdown = '''
Photo modes in other games — *Spider-Man: Miles Morales*, *Ratchet & Clank: Rift Apart*, etc. — have included a lighting mode feature, but *The Last of Us Part I* is the first game where I’ve actually taken the time to explore it.

Being able to add even just a single extra light to a scene allows for many more options in composing a shot.

Here’s an example of a shot of Joel in a cloud of spores. He’s backlit by Tess’s flashlight (lighting sources don’t always have to be environmental), which lights up the spore cloud to good effect, but leaves our subject without much detail.
'''

[[blocks]]
  type = 'image'
  key = 'tlou1_20221008222336'

[[blocks]]
  type = 'markdown'
  markdown = '''
Side note: I had to edit this first image slightly to match the final image for this example. There *is* a rim light in this scene, but it’s off to camera left and not adding much, aside from a small specular detail in part of the gas mask.

By adding a single low-intensity light opposite the backlight, we can bring out a lot more detail and depth to the shot — Joel’s eyes behind the mask, even a small reflection highlight in his own flashlight — without sacrificing the drama of the scene.
'''

[[blocks]]
  type = 'image'
  key = 'tlou1_20221008222606'

[[blocks]]
  type = 'markdown'
  markdown = '''
An extra fill or key light isn’t always necessary, of course. A wider shot of Joel in full silhouette in the spore cloud could also work well. Since it’s a close-up shot though, why not show off those great details?
'''
