[build]
  ## https://docs.netlify.com/configure-builds/troubleshooting-tips/#build-fails-on-warning-message
  command = "CI= npm run build:site"
  publish = "www/build"

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  external_node_modules = ["mdsvex"]

[[headers]]
  ## https://answers.netlify.com/t/content-type-header-not-working-in-netlify-toml/7718
  for = "/*"
[headers.values]
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  X-Clacks-Overhead = "GNU Terry Pratchett"
  X-Content-Type-Options = "nosniff"
  # cache just over 1 hour for webpagetest to be happy
  Cache-Control = "public, max-age=4000"

  ## Sanity slugify function changes `&` -> `and`.
  # [[redirects]]
  #   from = "/writing/update-capture-date-time-playstation-screenshots/"
  #   to = "/writing/update-capture-date-and-time-playstation-screenshots/"
