[[updates]]
  _type = 'post-add'
  date = 2023-05-07T21:31:45.805Z
  slug = 'can-never-look-photograph-twice'

[[updates]]
  _type = 'gallery-update'
  date = 2023-04-25T02:24:38.698Z
  slug = 'screen-shots/horizon-forbidden-west'
  count = 13

[[updates]]
  _type = 'gallery-update'
  date = 2023-03-04T03:00:34.973Z
  slug = 'screen-shots/star-wars-jedi-fallen-order'
  count = 14

[[updates]]
  _type = 'post-add'
  date = 2023-02-28T21:55:45.805Z
  slug = 'update-capture-date-time-playstation-screenshots'

[[updates]]
  _type = 'gallery-add'
  date = 2023-02-24T23:03:26.346Z
  slug = 'screen-shots/star-wars-jedi-fallen-order'

[[updates]]
  _type = 'note-add'
  date = 2023-02-15T17:41:13.532Z
  slug = '1676482873540'

[[updates]]
  _type = 'gallery-update'
  date = 2023-02-03T18:29:11.550Z
  slug = 'screen-shots/horizon-forbidden-west'
  count = 9

[[updates]]
  _type = 'gallery-update'
  date = 2023-01-14
  slug = 'screen-shots/a-plague-tale-innocence'
  count = 4

[[updates]]
  _type = 'post-add'
  date = 2022-12-17
  slug = 'difference-single-key-light-can-make'

[[updates]]
  _type = 'gallery-add'
  date = 2022-11-29T06:40:36.000Z
  slug = 'screen-shots/a-plague-tale-innocence'

[[updates]]
  _type = 'gallery-add'
  date = 2022-10-09T04:58:08.000Z
  slug = 'screen-shots/the-last-of-us-part-i'
