backend:
  name: github
  repo: tidaltheory/tidaltheory-www
  branch: main
  squash_merges: true

publish_mode: editorial_workflow

site_url: https://tidaltheory.io

media_folder: static/media
public_folder: /media

collections:
  - name: notes
    label: Notes
    label_singular: Note
    folder: content/notes
    create: true
    format: toml-frontmatter
    slug: '{{date_slug}}'
    fields:
      - { label: Date, name: date, widget: datetime }
      - { label: Date slug, name: date_slug, widget: datetime, format: 'x' }
      - { label: Updated, name: updated, widget: datetime }
      - { label: Body, name: body, widget: markdown }
      - label: Syndication
        name: syndication
        widget: list
        required: false
        fields:
          - { label: URL, name: url, widget: string }
